### ISSUE TITLE
Game is only loading local maps on the TV. 

### ISSUE THREAD

**Issue by chalkychelsea** [Foohy/jazztronauts#114]
I can't access any of the workshop maps. 
I've already reinstalled the game multiple times, reinstalled garry's mod, verified game files, the works. 
I've even fiddled with the console commands just to see if it'd do anything, but no such luck. The TV only shows maps from TF2 and L4D2 (and sometimes the other maps for jazztronauts, the ones that play for the intro and endings.)

**Comment by Foohy** [comment]
This is unfortunately on purpose, dynamically loading workshop maps is currently broken on the mainline gmod, so instead of it breaking and confusing people, it now loads local maps/addons and confuses people: https://github.com/Foohy/jazztronauts/issues/111 

Switching to the 'dev' branch in the gmod betas menu will re-enable the old behavior. Also, it will still load in maps from workshop addons that are already subscribed, but it just can't dynamically mount them.

**Comment by chalkychelsea** [comment]
Ah, gotcha. Thanks for letting me know!
