### ISSUE TITLE
What happened to the custom loading screen?

### ISSUE THREAD

**Issue by lazyRares** [Foohy/jazztronauts#195]
I just realized that the custom loading screen Jazztronauts used to have isn't present anymore. Did a GMOD patch break it?

**Comment by Commenter25** [comment]
I believe it was removed because it tended to stay on people's Gmod install even after completely uninstalling Jazztronauts. So every loading screen would be the Jazztronauts loading screen. However, it may have been broken by a patch as well. I plan on looking into this myself eventually, possibly restoring it if I can fix that issue.
