### ISSUE TITLE
Crashes on Linux with maximum settings enabled

### ISSUE THREAD

**Issue by xDShot** [Foohy/jazztronauts#37]
when I load bar map. the game crashes. Usually with no error messages, but once I caught this
![2018-08-05 18-13-21](https://user-images.githubusercontent.com/4261659/43687335-d925d31a-98db-11e8-8b06-640c6c9fe0bd.png)

**Comment by casKd-dev** [comment]
It is pretty obvious what the problem is, get more RAM.

**Comment by ThePotato97** [comment]
I'd get more ram but my motherboard doesn't support over 32 GB

**Comment by tatokis** [comment]
I have this error every now and then in gmod in general.

The problem is that gmod is a 32 bit binary and it hits the 3.X GB ram limit pretty quickly.
Adding more system ram won't help with this issue.

Other than lowering the graphics, you can disable pulseaudio's shared memory as that tends to use a few hundred megabytes of memory in the gmod process.

You can do that by setting 
```
enable-shm = no
```
in `/etc/pulse/client.conf`.

You can confirm this issue by running the steam client in a terminal, and then looking at the output when the game crashes.

The problem most likely lies with gmod itself, and there's not much that can be done about it.
