### ISSUE TITLE
Skipping full shard tank after level 2

### ISSUE THREAD

**Issue by mets11rap** [Foohy/jazztronauts#52]
I don't know if this is intention, but if you get 10 dark shards without completing all the quests first and play the cutscene, once you return to the lobby you'll be able to advance to the next level even if your shard tank isn't full

**Comment by Foohy** [comment]
It's by design, but unclear because of time constraints: Once you've finished the alternate ending, it'll show the podiums to reset to ng+ at the original shard tank. It's very shoehorned in as we still wanted the ability to play the game even after finishing an ending, but more and more I'm leaning towards the alternate ending just immediately resetting to ng+. 
(Normal ending would still allow it though, for players that just want to explore random maps and ignore story).

**Comment by mets11rap** [comment]
But you're not getting the actual ending; it says to complete all the cats' quests first.
