### ISSUE TITLE
Suggested changes for Auto-Auto Aim and more

### ISSUE THREAD

**Issue by SoraHjort** [Foohy/jazztronauts#63]
Hope this is a good place to put in suggested changes.

[Auto-Auto Aim Upgrade]

The upgrade has two annoying aspects to it, the miss SFX, and the jerking animation. Maybe it would be best to change it so that when held, it just has a low drone hum going. As well as having the stick being held forward (maybe like a wand?)

Atleast do something about the miss sound effect when you have the upgrade, as that can be headache inducing. The animation isn't as big of a deal in comparison to the SFX.

[Prop Tally]

When it's time to tally up the props back in the bar, it can get quite laggy. It would be nice to have an launch option, or mid-tally to not do a physical count. Something like pulling the lever again would stop the ghost props from spawning and just skip to the payout.

Just an option to not deal with the lag, nor the wait time to just jump into the next map would be nice.

[Shard Tank]

This is minor for me. But it would be nice if the shard tank remembered it's position between visits to the bar. As well as not bother with adding more past 100 shards. it just seems redundant to keep adding more into it.

**Comment by Foohy** [comment]
Hey I'm a little bit late to this one (woops), but:
1. For the auto aim upgrade, it's since been changed to slowly fade out the SFX when holding it down, so it's not nearly as grating on the ears, because you're right wow it was super annoying.
2. There's just been a change to allow you to change the speed in which props fall, slowing it down would help with lag, but you're right there's nothing to just 'skip ahead' right now. If you still want this 5 years later (oh god), I'd say make a specific issue for that to keep things compartmentalized.
3. Yeah I'm not married to it doing all at once, I just like hearing the effect start from nothing and go up every time. If you make a PR that changes it to only be the difference from the last map, I'd be willing to merge that in.

Due to this comment being... 5 years old and touching on a few random things, I'm going to close it for now, but please feel free to reopen ones for the specific suggestions, since it makes it a bit easier to compartmentalize the work. Thank you tons for the feedback though, and apologies for getting back to you so late here
