### ISSUE TITLE
Host and/or auto-generate the gamemode's map list on GitHub

### ISSUE THREAD

**Issue by VictorienXP** [Foohy/jazztronauts#85]
The domain might have expired or is misconfigured for some reason... @Foohy 

So the gamemode doesn't have a default list of maps anymore. And the loading screen is broken too.

If the domain/host isn't coming back there should be an newer alternative.

Like fetching these directly from GitHub (or GitHub "proxies") or maybe experimental stuff like [IPFS](https://ipfs.io/)...

**Comment by Foohy** [comment]
Hmm, I'm able to still access the list, is something blocking your access to http://host.foohy.net/public/Documents/Jazz/addons.txt ?

Though you're right, it'd rule to have it hosted on something a little more reliable (not that I intend to shut down foohy.net though, if anything I'd accidentally wipe it haha).
Perhaps use the new GitHub actions regenerate the addon list every now and then too? 

Also, the gamemode _does_ come with a (albeit very old...) default map list, but it's very possible that it didn't seem to work because it kept coming across removed/no longer valid workshop IDs. That's a bit harder to keep updated, but hosting on github would make it better than some random dude's webserver.

**Comment by VictorienXP** [comment]
Well the exact issue is that I can't resolve the domain anymore for some reasons.

I'm using [1.1.1.1](https://1.1.1.1/dns/) on a [pi.hole](https://pi-hole.net/) with DNSSEC... And I have both IPv4 and IPv6 working.

_I also have access to a dedicated server that also can't resolve, it's using whatever default DNS servers it has..._

According to the pi.hole query log the DNSSEC check failed and/or the response is entirely empty...
![image](https://user-images.githubusercontent.com/1633366/70489710-cf497500-1afc-11ea-81bf-794230a04e12.png)

**Comment by Foohy** [comment]
...Fixed? I turned a setting off and on in my registrar's nameserver settings and it seems to be resolving on 1.1.1.1 now. I do still want to move that list to github though, but fixed temporarily for now.

**Comment by VictorienXP** [comment]
Yes DNSSEC is working now!
![image](https://user-images.githubusercontent.com/1633366/70608287-27b56b00-1c00-11ea-8ca2-4bd409dd4f53.png)

**Comment by Foohy** [comment]
"done" in latest master commit. While I still host the addons.txt, but it is at least generated via GitHub Actions.
The missing feature in github actions is a direct link to the latest artifact, so for now it just sftp's in my server.
